auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
highlighter: pygments
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

